chore: create base repository for file manager
SoftDevSix/ArgosFileManager pull request #1
Opened 2024-11-25 04:56 UTC by GabyGV-GGV

## Related Tickets & US
- [CS-60](https://app.clickup.com/t/868b0381t)

## Description

- Continuous integration configuration and sonarqube.
- The project should run without any issues
- Create a new Spring Boot Project for manage unstructured data
It should have the correct dependencies for a NoSQL database or an AWS service.

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

This can be tested by running the following commands:

To view dependencies:

`./gradlew build`

To run the main class:

`./gradlew bootRun`

To run tests:

`./gradlew test`

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] I have checked my code and corrected any misspellings

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/SoftDevSix/ArgosFileManager/1)

2024-11-25 15:06 UTC, zrock-dev commented
Dear @gabygabylagaby, please add a description.

2024-11-25 15:49 UTC, teran-joseluis requested changes

2024-11-25 15:49 UTC, teran-joseluis commented on .github/workflows/check-push.yml
> +          accessToken: ${{ secrets.GITHUB_TOKEN }}
Don't forget to add the extra empty line.

2024-11-25 15:49 UTC, teran-joseluis commented on .github/workflows/checkout-pull-request.yml
> +          max_length: 100
Same here.

2024-11-25 15:49 UTC, teran-joseluis commented on .github/workflows/checkout-pull-request.yml
> +name: CI_Push_Workflow
Please rename the file according to the action.

2024-11-25 15:49 UTC, teran-joseluis commented on .github/workflows/sonar-scan.yml
> +        run: ./gradlew sonar --no-daemon
Same here about the extra line.

2024-11-25 15:49 UTC, teran-joseluis commented on .gradle/8.11.1/checksums/checksums.lock
You shouldn't upload theses files, please a `.gitignore` file for it.

2024-11-25 15:49 UTC, teran-joseluis commented on .idea/.gitignore
Same here about the `.gitignore` file. Delete them please.

2024-11-25 15:49 UTC, teran-joseluis commented on ArgosFileManager/.idea/gradle.xml
Already recommendation here.

2024-11-25 15:49 UTC, teran-joseluis commented on HELP.md
Same recommendation here.

2024-11-25 15:49 UTC, teran-joseluis commented on build/reports/problems/problems-report.html
Avoid uploading these files please. Use a `.gitignore` please

2024-11-25 15:49 UTC, teran-joseluis commented on build.gradle.kts
> +        property("sonar.host.url", "http://argos.japaneast.cloudapp.azure.com")
Please use environment variables for this line please and the next one too.

2024-11-25 15:50 UTC, GabyGV-GGV commented on .github/workflows/check-push.yml
> +          accessToken: ${{ secrets.GITHUB_TOKEN }}
Done

2024-11-25 15:50 UTC, GabyGV-GGV commented on .github/workflows/checkout-pull-request.yml
> +          max_length: 100
Done

2024-11-25 15:50 UTC, GabyGV-GGV commented on .github/workflows/checkout-pull-request.yml
> +name: CI_Push_Workflow
Done

2024-11-25 15:51 UTC, GabyGV-GGV commented on .github/workflows/sonar-scan.yml
> +        run: ./gradlew sonar --no-daemon
Done

2024-11-25 15:51 UTC, GabyGV-GGV commented on .idea/.gitignore
Done

2024-11-25 15:51 UTC, GabyGV-GGV commented on ArgosFileManager/.idea/gradle.xml
Done

2024-11-25 15:51 UTC, GabyGV-GGV commented on HELP.md
Done

2024-11-25 15:51 UTC, GabyGV-GGV commented on build.gradle.kts
> +        property("sonar.host.url", "http://argos.japaneast.cloudapp.azure.com")
Done

2024-11-25 16:14 UTC, teran-joseluis approved these changes

2024-11-25 20:18 UTC, zrock-dev requested changes
> *[Reviewable](https://reviewable.io/reviews/SoftDevSix/ArgosFileManager/1)* status: 0 of 40 files reviewed, 11 unresolved discussions (waiting on @gabygabylagaby, @sebastian-barra-jalafund, @teran-joseluis, and @zamoranoalicia)

___
*[`build.gradle.kts` line 22 at r3](https://reviewable.io/reviews/SoftDevSix/ArgosFileManager/1#-OCZxkCB4loov2j-9wqO:-OCZxkCCCzW8IdhgBI4r:bhno8yo) ([raw file](https://github.com/SoftDevSix/ArgosFileManager/blob/543e98046ef7fdec7260a126efa05166148cb96e/build.gradle.kts#L22)):*
> ```Kotlin
>     val sonarHostUrl = System.getenv("SONAR_HOST_URL") ?: ""
>     val sonarToken = System.getenv("SONAR_TOKEN") ?: ""
>     properties {
> ```

Following our convention about dependencies, please update this build file to fetch dependencies from `gradle/libs.versions.toml`. Check the [Argos](https://github.com/SoftDevSix/Argos) as an example.


<!-- Sent from Reviewable.io -->

2024-11-25 20:25 UTC, sebastian-barra-jalafund approved these changes

2024-11-26 04:39 UTC, GabyGV-GGV commented
@zrock-dev Done

2024-11-26 13:59 UTC, zrock-dev approved these changes
LGTM

2024-11-27 06:50 UTC, merged